### ISSUE TITLE
Login: should remove -p option

### ISSUE THREAD

**Issue by sebasgarcep** [expo/exp#24]
It is fundamentally unsafe as terminals are often logged by default. Having a -p option encourages unsafe behaviour.

**Comment by dikaiosune** [comment]
Hi @sebasgarcep, thanks for the report. I think you're probably right here, and this has been on our radar for a little bit. We're currently working on overhauling a bunch of our authentication stuff, and I expect we'll be able to support a token-based environment variable instead of the CLI password flag soon.

We're hoping to have this in place sometime in January 2017, and I'll update this issue once it's available.

**Comment by brentvatne** [comment]
tracking in https://github.com/expo/expo/issues/172
