### ISSUE TITLE
[Support] :exp cli on NPM v5.x

### ISSUE THREAD

**Issue by GeekRishabh** [expo/exp#93]
Can you guys please support for exp cli on NPM v5.x . Its a pain every time to change NPM version or use expo XDE tool .as all task can't be done using XDE Please look into it .
I am sharing the error log below 
```
ngrok - error unpacking binary { Error: EACCES: permission denied, open '/usr/local/lib/node_modules/exp/node_modules/@expo/ngrok/bin/ngrok'
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/usr/local/lib/node_modules/exp/node_modules/@expo/ngrok/bin/ngrok' }
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @expo/traveling-fastlane-linux@1.0.15 (node_modules/exp/node_modules/@expo/traveling-fastlane-linux):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @expo/traveling-fastlane-linux@1.0.15: wanted {"os":"win32,linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})
```

**Comment by dikaiosune** [comment]
Hi! This doesn't look like an npm 5 issue to me, although if it doesn't happen with yarn, then I guess that's your answer. Regardless, make sure your directory permissions for your global node_modules are sane (owned and writable by your user accounts). In terms of supporting npm 5, the change broke a lot of things, not all of which have been fixed in recent npm releases. We'll try to figure out what we can do soon, but because there are other options (npm 4, yarn), it's honestly not the highest priority thing we're trying to fix.

Also, as the issue template requests, please open issues against https://github.com/expo/expo.
